"""create intakes table

Revision ID: 1259b99d5b02
Revises: 
Create Date: 2026-08-10 13:14:06.740581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1259b99d5b02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intakes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disease_context', sa.String(length=50), nullable=False),
    sa.Column('visit_purpose', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('symptom_change', sa.String(length=30), nullable=True),
    sa.Column('document_type', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('document_destination', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('patient_present', sa.Boolean(), nullable=False),
    sa.Column('guardian_only', sa.Boolean(), nullable=False),
    sa.Column('requested_consultation', sa.Text(), nullable=True),
    sa.Column('subjective_summary', sa.Text(), nullable=False),
    sa.Column('soap_summary', sa.Text(), nullable=False),
    sa.Column('raw_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intakes')
    # ### end Alembic commands ###
