"""add flagged_for_review to intakes

Revision ID: b53e199ec241
Revises: 1259b99d5b02
Create Date: 2026-09-23 15:51:37.559986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53e199ec241'
down_revision: Union[str, Sequence[str], None] = '1259b99d5b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'intakes',
        sa.Column('flagged_for_review', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('intakes', 'flagged_for_review', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intakes', 'flagged_for_review')
    # ### end Alembic commands ###
